CREATE DATABASE mvc_tp;
USE mvc_tp;

CREATE TABLE `user` (
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT, 
email VARCHAR(100) NOT NULL UNIQUE, 
password_hash VARCHAR(255) NOT NULL,
nom VARCHAR(100),
prenom VARCHAR(100),
adresse VARCHAR(255)
);
